spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: reservation
    password: reservation
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
